stack:
  config:
    hierarchy-merge: true
    storege: false
  stackweb:
    name: stack.web.stackweb
    address: 127.0.0.1
    port: 8082
    api-path: /api/v1
    root-path: /stack
    static-dir:
    favicon-ico:
  registry:
    name: zookeeper
    address: 10.177.98.176:2181,10.177.98.177:2181,10.177.98.178:2181
  logger:
    name: slogrus
    level: info